[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg-native"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
